const FETCH_USER = "FETCH_USER";
const FETCH_ERROR = "FETCH_ERROR";
const START_REGISTRATION = "START_REGISTRATION";
const SUCCESSFUL_REGISTRATION = "SUCCESSFUL_REGISTRATION";
const REGISTRATION_FAILED = "REGISTRATION_FAILED";
const START_LOGGING_IN = "START_LOGGING_IN";
const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN";
const LOGIN_FAILED = "LOGIN_FAILED";
const START_VERIFICATION = "START_VERIFICATION";
const SUCCESSFUL_VERIFICATION = "SUCCESSFUL_VERIFICATION";
const VERIFICATION_FAILED = "VERIFICATION_FAILED";
const START_FORGOT_PASSWORD = "START_FORGOT_PASSWORD";
const SUCCESS_FORGOT_PASSWORD = "SUCCESS_FORGOT_PASSWORD";
const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";
const START_RESET_PASSWORD = "START_RESET_PASSWORD";
const SUCCESS_RESET_PASSWORD = "SUCCESS_RESET_PASSWORD";
const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
const START_RETRIEVING_QUICKBOOKS_ACCESS_TOKEN =
  "START_RETRIEVING_QUICKBOOKS_ACCESS_TOKEN";
const RECEIVED_QUICKBOOKS_ACCESS_TOKEN = "RECEIVED_QUICKBOOKS_ACCESS_TOKEN";
const FAILED_RETRIEVING_QUICKBOOKS_ACCESS_TOKEN =
  "FAILED_RETRIEVING_QUICKBOOKS_ACCESS_TOKEN";
const START_STEP_ONE_QUESTIONNAIRE = "START_STEP_ONE_QUESTIONNAIRE";
const QUESTIONNAIRE_STEP_ONE_SUCCESS = "QUESTIONNAIRE_STEP_ONE_SUCCESS";
const QUESTIONNAIRE_STEP_ONE_FAILED = "QUESTIONNAIRE_STEP_ONE_FAILED";
const START_STEP_TWO_QUESTIONNAIRE = "START_STEP_TWO_QUESTIONNAIRE";
const QUESTIONNAIRE_STEP_TWO_SUCCESS = "QUESTIONNAIRE_STEP_TWO_SUCCESS";
const QUESTIONNAIRE_STEP_TWO_FAILED = "QUESTIONNAIRE_STEP_TWO_FAILED";
const START_STEP_THREE_QUESTIONNAIRE = "START_STEP_THREE_QUESTIONNAIRE";
const QUESTIONNAIRE_STEP_THREE_SUCCESS = "QUESTIONNAIRE_STEP_THREE_SUCCESS";
const QUESTIONNAIRE_STEP_THREE_FAILED = "QUESTIONNAIRE_STEP_THREE_FAILED";
const FETCH_BANKS = "FETCH_BANKS";
const FETCH_BANKS_FAILED = "FETCH_BANKS_FAILED";

export {
  FETCH_USER,
  FETCH_ERROR,
  START_REGISTRATION,
  SUCCESSFUL_REGISTRATION,
  REGISTRATION_FAILED,
  START_LOGGING_IN,
  SUCCESSFUL_LOGIN,
  LOGIN_FAILED,
  START_VERIFICATION,
  SUCCESSFUL_VERIFICATION,
  VERIFICATION_FAILED,
  START_FORGOT_PASSWORD,
  SUCCESS_FORGOT_PASSWORD,
  FORGOT_PASSWORD_FAILED,
  START_RESET_PASSWORD,
  SUCCESS_RESET_PASSWORD,
  RESET_PASSWORD_FAILED,
  START_RETRIEVING_QUICKBOOKS_ACCESS_TOKEN,
  RECEIVED_QUICKBOOKS_ACCESS_TOKEN,
  FAILED_RETRIEVING_QUICKBOOKS_ACCESS_TOKEN,
  START_STEP_ONE_QUESTIONNAIRE,
  QUESTIONNAIRE_STEP_ONE_SUCCESS,
  QUESTIONNAIRE_STEP_ONE_FAILED,
  START_STEP_TWO_QUESTIONNAIRE,
  QUESTIONNAIRE_STEP_TWO_SUCCESS,
  QUESTIONNAIRE_STEP_TWO_FAILED,
  START_STEP_THREE_QUESTIONNAIRE,
  QUESTIONNAIRE_STEP_THREE_SUCCESS,
  QUESTIONNAIRE_STEP_THREE_FAILED,
  FETCH_BANKS,
  FETCH_BANKS_FAILED
};
